# fly.toml app configuration file generated for dawn-glade-5740 on 2023-08-02T12:53:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-glade-5740"
primary_region = "atl"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[deploy]
release_command = "npm run migrate up"
